### ISSUE TITLE
Unhandled 'error' event

### ISSUE THREAD

**Issue by colinskow** [TooTallNate/node-agent-base#10]
I am getting this occasionally with both the https and socks adaptors. I am using a custom agent with needle and using a promise with catch, which does get most errors but sometimes something slips through and crashes my entire app. I believe you need to add an on `error` handler to the TLS and sockets objects.

```
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at exports._errnoException (util.js:1018:11)
    at TLSWrap.onread (net.js:568:26)
```

**Comment by TooTallNate** [comment]
This code in this repository has been moved to the [`proxy-agents` monorepo](https://github.com/TooTallNate/proxy-agents), so I am closing this pull request. If you feel that this issue still exists as of the latest release, feel free to open a new issue over there.
