### ISSUE TITLE
Module breaks in ie11

### ISSUE THREAD

**Issue by jacopotarantino** [TooTallNate/node-agent-base#12]
On line 137 of index.js there’s a template literal which IE11 somehow still doesn’t support. Please either provide a compiled version of the module or change that line to a regular string so that IE11 can parse the whole module.

**Comment by TooTallNate** [comment]
Patch welcome. However, this module is not intended for use in the web browser, so I'm not sure why you would be executing it in IE11.

**Comment by jacopotarantino** [comment]
I thought about this long and hard and came to a couple conclusions: first, you're totally right. Don't run software where it's clearly not intended to be run and expect support. Second, my team ran into this as part of a botched webpack config(isomorphic react gone wrong) and I don't want other people to be clocked by this even if it's not actually a bug at all. I'll submit a PR shortly.

**Comment by jacopotarantino** [comment]
Also sorry to open an issue for something I could have submitted a PR for. Can't do it at my dayjob so it had to wait until I could work on OSS from my home computer.
