### ISSUE TITLE
Module fails to minify 

### ISSUE THREAD

**Issue by soorajvnair** [TooTallNate/node-agent-base#16]
Hey there,

I'm unable to run the minify process on one of my apps created using Create React App cli,
i get the following error, 
![screen shot 2018-01-31 at 8 20 58 pm](https://user-images.githubusercontent.com/4268932/35629387-8099ed70-06c4-11e8-9919-7c9010ca8253.png)
The reason why it fails is detailed here. https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-build-fails-to-minify

**Comment by sstant** [comment]
+1

**Comment by Tornaldo** [comment]
As a temporary measure we can go into /node_modules/agent-base and fix it ourselves. The problem has to do with modern JavaScript features (such as using let instead of var) are being used.

I changed /node_modules/agent-base/patch-core.js to this (I removed some comments from the code because of formating-problems in the github text-editor I'm writing in now):

> 'use strict';
> const url = require('url');
> const https = require('https');
> 
> https.request = (function(request) {
>   return function(_options, cb) {
>     var options;
>     if (typeof _options === 'string') {
>       options = url.parse(_options);
>     } else {
>       options = Object.assign({}, _options);
>     }
>     if (null == options.port) {
>       options.port = 443;
>     }
>     options.secureEndpoint = true;
>     return request.call(https, options, cb);
>   };
> })(https.request);
> 
> https.get = function(options, cb) {
>   const req = https.request(options, cb);
>   req.end();
>   return req;
> };
> 

And I changed /node_modules/agent-base/index.js to this:

> 'use strict';
> require('./patch-core');
> const inherits = require('util').inherits;
> const promisify = require('es6-promisify');
> const EventEmitter = require('events').EventEmitter;
> 
> module.exports = Agent;
> 
> function isAgent(v) {
>   return v && typeof v.addRequest === 'function';
> }
> 
> function Agent(callback, _opts) {
>   if (!(this instanceof Agent)) {
>     return new Agent(callback, _opts);
>   }
> 
>   EventEmitter.call(this);
> 
>   // The callback gets promisified if it has 3 parameters
>   // (i.e. it has a callback function) lazily
>   this._promisifiedCallback = false;
> 
>   var opts = _opts; // let opts = _opts;
>   if ('function' === typeof callback) {
>     this.callback = callback;
>   } else if (callback) {
>     opts = callback;
>   }
> 
>   // timeout for the socket to be returned from the callback
>   this.timeout = (opts && opts.timeout) || null;
> 
>   this.options = opts;
> }
> inherits(Agent, EventEmitter);
> 
> Agent.prototype.callback = function callback(req, opts) {
>   throw new Error(
>     '"agent-base" has no default implementation, you must subclass and override `callback()`'
>   );
> };
> 
> Agent.prototype.addRequest = function addRequest(req, _opts) {
>   const ownOpts = Object.assign({}, _opts);
> 
>   // Set default `host` for HTTP to localhost
>   if (null == ownOpts.host) {
>     ownOpts.host = 'localhost';
>   }
> 
>   // Set default `port` for HTTP if none was explicitly specified
>   if (null == ownOpts.port) {
>     ownOpts.port = ownOpts.secureEndpoint ? 443 : 80;
>   }
> 
>   const opts = Object.assign({}, this.options, ownOpts);
> 
>   if (opts.host && opts.path) {
>     // If both a `host` and `path` are specified then it's most likely the
>     // result of a `url.parse()` call... we need to remove the `path` portion so
>     // that `net.connect()` doesn't attempt to open that as a unix socket file.
>     delete opts.path;
>   }
> 
>   delete opts.agent;
>   delete opts.hostname;
>   delete opts._defaultAgent;
>   delete opts.defaultPort;
>   delete opts.createConnection;
> 
>   // Hint to use "Connection: close"
>   // XXX: non-documented `http` module API :(
>   req._last = true;
>   req.shouldKeepAlive = false;
> 
>   // Create the `stream.Duplex` instance
>   var timeout; // let timeout;
>   var timedOut = false; // let timedOut = false;
>   const timeoutMs = this.timeout;
> 
>   function onerror(err) {
>     if (req._hadError) return;
>     req.emit('error', err);
>     // For Safety. Some additional errors might fire later on
>     // and we need to make sure we don't double-fire the error event.
>     req._hadError = true;
>   }
> 
>   function ontimeout() {
>     timeout = null;
>     timedOut = true;
>     const err = new Error(
>       'A "socket" was not created for HTTP request before ' + timeoutMs + 'ms'
>     );
>     err.code = 'ETIMEOUT';
>     onerror(err);
>   }
> 
>   function callbackError(err) {
>     if (timedOut) return;
>     if (timeout != null) {
>       clearTimeout(timeout);
>       timeout = null;
>     }
>     onerror(err);
>   }
> 
>   function onsocket(socket) {
>     if (timedOut) return;
>     if (timeout != null) {
>       clearTimeout(timeout);
>       timeout = null;
>     }
>     if (isAgent(socket)) {
>       // `socket` is actually an http.Agent instance, so relinquish
>       // responsibility for this `req` to the Agent from here on
>       socket.addRequest(req, opts);
>     } else if (socket) {
>       req.onSocket(socket);
>     } else {
>       const err = new Error(
>         'no Duplex stream was returned to agent-base for ' + req.method + ' ' + req.path
>       );
>       onerror(err);
>     }
>   }
> 
>   if (!this._promisifiedCallback && this.callback.length >= 3) {
>     // Legacy callback function - convert to a Promise
>     this.callback = promisify(this.callback, this);
>     this._promisifiedCallback = true;
>   }
> 
>   if (timeoutMs > 0) {
>     timeout = setTimeout(ontimeout, timeoutMs);
>   }
> 
>   try {
>     Promise.resolve(this.callback(req, opts)).then(onsocket, callbackError);
>   } catch (err) {
>     Promise.reject(err).catch(callbackError);
>   }
> };

**Comment by rohaldbUni** [comment]
+1

**Comment by tlycken** [comment]
I'm seeing this error too; and monkey-patching with the code @Tornaldo suggested (thanks for sharing!) seems to work. I simply put the files in a folder outside of `node_modules` together with a shell-script that copies them into `node_modules/agent-base`, and run that script as part of the build chain.

@TooTallNate is there some progress on releasing a version that doesn't require monkey-patching like this?

**Comment by tlycken** [comment]
I found a way to do what I needed with https://www.npmjs.com/package/fetch-with-proxy instead, so I'm no longer dependent on this package.

**Comment by Darwinium** [comment]
The same problem

**Comment by BYK** [comment]
Looks like the solution is to upgrade your `react-scripts` to something newer than 2.0.0 which is already quite old: https://facebook.github.io/create-react-app/docs/troubleshooting#npm-run-build-fails-to-minify
