### ISSUE TITLE
[test-fails] Agent artificial "streams" should receive a GET response

### ISSUE THREAD

**Issue by Shinigami92** [TooTallNate/node-agent-base#19]
When I run all tests, this test is failing:

1) Agent artificial "streams" should receive a GET response:
     `Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.`

---

```
$ npm -v
6.1.0
$ node -v
v10.4.0
```

**Comment by TooTallNate** [comment]
Thanks for the report. Fixed.
