### ISSUE TITLE
Add typescript or typescript-declaration

### ISSUE THREAD

**Issue by Shinigami92** [TooTallNate/node-agent-base#20]
I'm working on typescript declaration for your project.

Why? https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/node-configuring-proxies.html
Your package is suggested in the documentation of the AWS SDK and our projects are written in typescript

typescript complains about the missing type script declarations

Current branches/fork:

- https://github.com/Shinigami92/node-agent-base/tree/feature/typescript
  (all test are running successful)
- https://github.com/Shinigami92/node-agent-base/tree/feature/typescript-declaration
  (only declarations, no changes of the real code)

![agent-examples](https://user-images.githubusercontent.com/7195563/43220985-c488e962-904b-11e8-9496-b7b2591e0b2b.png)

**Comment by Shinigami92** [comment]
I just did a PR for the 2nd solution because it's better for the 1st solution to rewrite everything to ES2015+ and make a breaking change

because the use of `function Agend` and `new Agent` in this function is no longer compatible with ES2015+ / typescript
this is a very old style (never seen before ^^)

**Comment by Shinigami92** [comment]
This is generally a preparation for the fork https://github.com/Shinigami92/node-proxy-agent
That's my real goal :)

**Comment by Shinigami92** [comment]
I think because of [.gitignore#L3](https://github.com/TooTallNate/node-agent-base/blob/master/.gitignore#L3) `/?.js` the index.d.ts is missing in release 4.2.1

**Comment by BYK** [comment]
Closing as this is solved in #21. @Shinigami92 please reopen or create a new issue if you wanna do more or need more :)
