### ISSUE TITLE
Update https.request signature

### ISSUE THREAD

**Issue by AaronSharp5** [TooTallNate/node-agent-base#29]
**Tell us about your environment:**
* Agent-base version: 4.3.0
* Node.js version: 10.15.3

In this issue: https://github.com/TooTallNate/node-agent-base/issues/24, you updated node-agent-base so that users can still use the 3-argument https.get function specified by the node documentation: https://nodejs.org/api/https.html#https_https_get_url_options_callback.

The node documentation also specifies a 3-argument version of https.request: https://nodejs.org/api/https.html#https_https_request_url_options_callback.

Please apply the same fix to https.request that you applied to https.get.

**Comment by emersonford** [comment]
@meimei13 and I discovered this is causing some pretty nasty bugs. Reproduced these bugs using https://github.com/meimei13/https-reproduction. 

First, any usage of the `url` in https://nodejs.org/api/https.html#https_https_request_url_options_callback will not work with the patched `request`. As this patches `request` for the whole runtime, it's really difficult to trace where the error came from. In addition, the bugs manifest in two ways:
1. If `url` is a string, then the `request` will error out with `TypeError [ERR_INVALID_ARG_TYPE]: The "listener" argument must be of type Function. Received type object`.
2. If `url` is a url.URL object, the `host` and `hostname` will be dropped and default to `localhost`. This can either result in a `ECONNREFUSED` or, potentially even worse, fail silently if something is listening on `localhost:443`.

Pull request #30 updates the signature.

**Comment by emersonford** [comment]
I think it's probably worth moving the `if (null == options.port) { options.port = 443; }` and `options.secureEndpoint = true` bits upstream into nodejs's `request` method as the getting out of sync can cause some serious bugs from the looks of it. 

@meimei13 is planning on creating a pull request to push these upstream as suggested by the commenting on the patched `request` method.
