### ISSUE TITLE
Confusing Example

### ISSUE THREAD

**Issue by cawoodm** [TooTallNate/node-agent-base#33]
I stumbled across this module looking for a way to share HTTP connections upstream in a NodeJS application which is basically a reverse proxy. So it's kinda confusing when looking for an example that the [readme](https://github.com/TooTallNate/node-agent-base) provides and example of non-shared connections and no example of shared connections.

You write:
> Here's a minimal example that creates a new net.Socket connection to the server for every HTTP request (i.e. the equivalent of agent: false option):

This is at best an edge-case: I thought the whole point of using `http.Agent` was to pool connections.

Could you add a realistic example?

**Comment by TooTallNate** [comment]
This code in this repository has been moved to the [`proxy-agents` monorepo](https://github.com/TooTallNate/proxy-agents), so I am closing this pull request. If you feel that this issue still exists as of the latest release, feel free to open a new issue over there.
