### ISSUE TITLE
Twistlock scanning flags the test directory as contianing TLS Keys 

### ISSUE THREAD

**Issue by davecrighton** [TooTallNate/node-agent-base#34]
The IBM Product App Connect Enterprise has node-agent-base as an indirect dependency. We have a customer who is scanning docker images created as part of their CI/CD pipeline with the Twistlock security tool.

This is flagging the test keys in the test directory as being secure credential stored in the clear as described in the Embedded Secret Detection and Blocking section here:

https://www.twistlock.com/2017/04/17/introducing-twistlock-2-0/

We have informed our customer that we believe that removal of these files from the image will not adversely affect the function of the code and allow them to pass their security scans but wonder if the test data could be refactored to avoid the problem.

**Comment by bvwells** [comment]
We are also having this issue with Twisklock flagging the test data as an issue. Hopefully PR #37 should fix the issue.

**Comment by davecrighton** [comment]
Thanks @bvwells! Really appreciate the help.

**Comment by TooTallNate** [comment]
Please try out [`v5.0.0`](https://github.com/TooTallNate/node-agent-base/releases/tag/5.0.0), which no longer includes the `test` directory in the npm package.

**Comment by bvwells** [comment]
Thanks @TooTallNate! I'll give it a go.
