### ISSUE TITLE
Don't patch core methods

### ISSUE THREAD

**Issue by xPaw** [TooTallNate/node-agent-base#35]
It's just causing problems in unrelated code even when your dependency is not used.

https://github.com/sindresorhus/got/issues/951
https://github.com/sindresorhus/got/issues/941
https://github.com/TooTallNate/node-https-proxy-agent/issues/88

I'm not using `https-proxy-agent` directly, but the mere fact it's included by `web-push` (which we do use) breaks our app.

**Comment by dashmug** [comment]
I have the same problem. It breaks my app even if my app does not directly use `node-https-proxy-agent`.

**Comment by TooTallNate** [comment]
Thanks for the heads up. Please see https://github.com/TooTallNate/node-agent-base/pull/36 for my proposed solution.

**Comment by ouraios** [comment]
@TooTallNate When do you think you'll be able to fix this issue ? I saw that you had a working pull request, what's missing ?

**Comment by TooTallNate** [comment]
@ouraios Nothing is missing, I was just leaving the PR open for a bit to give anyone a chance to chime in if there is a problem with the fix.

**Comment by dguo** [comment]
@TooTallNate, thanks for the fix. Do you know when you'll be able to publish it to npm?

**Comment by ouraios** [comment]
I agree with @dguo , can you do a minor version release, so every package using `agent-base` will automatically upgrade to this fixed version ?

**Comment by ouraios** [comment]
I agree with @dguo , @TooTallNate can you do a minor version release, so every package using `agent-base` will automatically upgrade to this fixed version ?

**Comment by fengkx** [comment]
I think `socks-proxy-agent` need to upgrade the agent-base dependency too.

**Comment by hildoer** [comment]
For those of plagued by this in a rats nest of upstream dependencies that include this library, I have simply done this in a postinstall hook. Undoubtedly it breaks something in the upstream dependencies that are dependent on a polluted HTTPS core module, but my code isn't executing that code. 

```find node_modules/ | grep 'agent-base/patch-core' | xargs truncate -s 0```

Basically, after npm install this clears out every instance of agent-base/patch-core by any upstream dependency. 

It is a hack to fix a hack, but it has us working again as all of our automated tests are passing again without losing the functionality of the upstream dependencies we actually use.
