### ISSUE TITLE
semver error "throw new TypeError('Invalid Version: ' + version)" caused by empty version string

### ISSUE THREAD

**Issue by jaceyshome** [TooTallNate/node-agent-base#4]
Hi Nathan,

I faced an issue with node-agent-base/patch-core.js, line 11, when calling the function semver.lt(process.version, '0.11.8'), the process.version is an empty string, which cause an error. 

In "node-agent-base/patch-core.js"
<img width="1084" alt="screen shot 2016-06-03 at 12 56 49 am" src="https://cloud.githubusercontent.com/assets/5277867/15749759/e586797e-2926-11e6-8a2f-4645713a9232.png">

semver.js shows an error:
<img width="794" alt="screen shot 2016-06-03 at 12 57 47 am" src="https://cloud.githubusercontent.com/assets/5277867/15749766/eb85c668-2926-11e6-8037-7abf7d71adc6.png">

I think it is an issue with the empty version string, I am using browserify with node-browserstack, which is using this library to talk to Browserstack in browser not the nodejs environment. Without this if block, everything works. 

Any idea? I think it might be good to add a condition for the empty version string. 

Thanks,
Jake

**Comment by vitor251093** [comment]
I had that problem and I found the solution in my case: basically, when you use `cordova --version` for the first time, cordova asks if you will provide information anonymously to help improve cordova, and that question is mistakenly taken has the version. If you use `cordova --version` manually in the terminal and say Yes or No to that question, that problem will stop happening.
