### ISSUE TITLE
Sourcemaps point to non-existent .ts files

### ISSUE THREAD

**Issue by qtiki** [TooTallNate/node-agent-base#41]
The sourcemaps included in the dist files point to ../../src/ but the original TypeScript files aren't included in the distribution. When using Webpack with source-map-loader this leads to a couple of warnings like this:
```
WARNING in ./agent-base/dist/src/index.js
Module Warning (from ./node_modules/source-map-loader/index.js):
(Emitted value instead of an instance of Error) Cannot find source file '../../src/index.ts': Error: Can't resolve '../../src/index.ts' in '...\node_modules\agent-base\dist\src'
```

As I see it there are 3 options for getting rid of the warnings:

A) Include the source code in the sourcemaps using tsconfig --inlineSources option
B) Include the src directory in the distribution with all of the original .ts files
C) Disable sourcemaps alltogether

**Comment by TooTallNate** [comment]
Thanks for pointing this out! Fixed with option **B** in #45.
