### ISSUE TITLE
Doesn't work with @types/node@14

### ISSUE THREAD

**Issue by hipstersmoothie** [TooTallNate/node-agent-base#43]
Trying to upgrade my types for node on this project https://github.com/intuit/auto/pull/1317

I get this error

![Screen Shot 2020-07-01 at 9 18 37 AM](https://user-images.githubusercontent.com/1192452/86267626-d957c180-bb7b-11ea-93bb-8e3d41736d9b.png)

It looks like this is something that would need to be added to the library here. I am unsure of how to do this myself

![Screen Shot 2020-07-01 at 9 19 20 AM](https://user-images.githubusercontent.com/1192452/86267689-f42a3600-bb7b-11ea-919a-eb05c868d7fb.png)

**Comment by TooTallNate** [comment]
Fixed by #46.
