### ISSUE TITLE
Why are certs unsigned? 

### ISSUE THREAD

**Issue by Javaman2** [TooTallNate/node-agent-base#44]
Just wondering why the certs are unsigned?

**Comment by TooTallNate** [comment]
Which certs?

**Comment by Javaman2** [comment]
[These certs](https://github.com/TooTallNate/node-agent-base/tree/master/test) are being flagged in my Angular compile. So I thought I'd ask you about them.

**Comment by TooTallNate** [comment]
Right, they're self-signed certs for use with the tests. They should not be included in the npm package though, which version of `agent-base` are you using?

**Comment by TooTallNate** [comment]
See https://github.com/TooTallNate/node-agent-base/issues/34 which is more or less a duplicate of this one.

**Comment by Javaman2** [comment]
Thanks TooTall!
