### ISSUE TITLE
Node@12 Property 'maxTotalSockets' is missing in type 'HttpsProxyAgent'

### ISSUE THREAD

**Issue by dobromyslov** [TooTallNate/node-agent-base#48]
Type 'HttpsProxyAgent' is not assignable to type 'Agent | ((parsedUrl: URL) => Agent)'.   Property 'maxTotalSockets' is missing in type 'HttpsProxyAgent' but required in type 'Agent'.

* @types/node@~12.19.0 contains http.Agent class with mandatory maxTotalSockets property.
* @types/node-fetch@2.5.7 RequestInit interface uses Agent from Node http.
* https-proxy-agent@5.0.0 uses Agent class from agent-base@6 which has no maxTotalSockets property.

Therefore it's impossible to assign HttpsProxyAgent to the node-fetch's agent.

See https://github.com/TooTallNate/node-https-proxy-agent/issues/114

**Comment by dobromyslov** [comment]
Node docs https://nodejs.org/api/http.html#http_agent_maxtotalsockets:

> agent.maxTotalSockets#
Added in: v14.5.0, v12.19.0
<number>

> By default set to Infinity. Determines how many concurrent sockets the agent can have open. Unlike maxSockets, this parameter applies across all origins.

**Comment by tylersmalley** [comment]
Thanks @TooTallNate, would you mind pushing publishing a release for http-proxy-agent with this update?

**Comment by TooTallNate** [comment]
@tylersmalley Shouldn't be necessary, since `http-proxy-agent` uses a "loose" version number, so running `yarn update` should work.
