### ISSUE TITLE
Support for keepalive?

### ISSUE THREAD

**Issue by wiliame** [TooTallNate/node-agent-base#5]
Looking at the code it seems that there isn't support for keep-alive right?

**Comment by TooTallNate** [comment]
There isn't support at the moment, but I'd accept a pull request. The tricky part is making it generic enough that all the implementations that use this module get support too.

**Comment by wiliame** [comment]
@TooTallNate ok thanks for the fast response.

I found "tunnel-agent", it's supposed to support it, the package is part of the "request" node module.
https://github.com/request/tunnel-agent

For now I have implemented it with native node libraries for HTTP, I'm now with HTTPS. When I get some more experience with agents and tunneling I will try (maybe) to implement the feature using "node-agent-base".

**Comment by coolhandfluke** [comment]
@wiliame Can I use the tunnel-agent with keep alive option behind proxy for https requests?

**Comment by TooTallNate** [comment]
This code in this repository has been moved to the [`proxy-agents` monorepo](https://github.com/TooTallNate/proxy-agents), so I am closing this pull request. If you feel that this issue still exists as of the latest release, feel free to open a new issue over there.
