### ISSUE TITLE
TLS issue

### ISSUE THREAD

**Issue by greghmerrill** [TooTallNate/node-agent-base#51]
I just upgraded to pac-proxy-agent 4.1.0, which uses node-agent-base 6.0.2.

After upgrading, I noticed that when I made requests to URLs which were mapped to DIRECT entries in my PAC file, I was getting this error:

`RequestError: Error: write EPROTO 1976418680:error:10000438:SSL routines:OPENSSL_internal:TLSV1_ALERT_INTERNAL_ERROR:../../third_party/boringssl/src/ssl/tls_record.cc:586:SSL alert number 80`

After some debugging, I found that by setting "servername" on the opts object in addRequest, the issue was resolved.

`opts.servername = opts.host;`

I came to this conclusion after carefully examining the options object when calling the same URL while not using the pac-proxy-agent (which didn't suffer from this issue).  There I observed that the default agent sets the servername.

I'm not familiar enough with nodejs & agents to know if my fix for the problem is correct but thought I would pass it along.

**Comment by TooTallNate** [comment]
This code in this repository has been moved to the [`proxy-agents` monorepo](https://github.com/TooTallNate/proxy-agents), so I am closing this pull request. If you feel that this issue still exists as of the latest release, feel free to open a new issue over there.
