### ISSUE TITLE
Cannot read property 'startsWith' of undefined error 

### ISSUE THREAD

**Issue by sathish-1997** [TooTallNate/node-agent-base#52]
hi guys im facing this error when im doing edit. it was working before i put in a custom resolver & data loader. Now even if command the customer resolver & data loader i get this error
![startWith](https://user-images.githubusercontent.com/57295985/99649317-08b98d00-2a8f-11eb-8c8f-6c4ff1ae9a3b.PNG)

**Comment by TooTallNate** [comment]
This code in this repository has been moved to the [`proxy-agents` monorepo](https://github.com/TooTallNate/proxy-agents), so I am closing this pull request. If you feel that this issue still exists as of the latest release, feel free to open a new issue over there.
