### ISSUE TITLE
Broken with typescript 4.1.2

### ISSUE THREAD

**Issue by merkys** [TooTallNate/node-agent-base#53]
node-agent-base fails to build from source with typescript 4.1.2:

```
$ tsc
src/promisify.ts(27,15): error TS2345: Argument of type 'Duplex | Pick<Agent, "addRequest"> | Agent | undefined' is not assignable to parameter of type 'Duplex | Pick<Agent, "addRequest"> | Agent | PromiseLike<AgentCallbackReturn>'.
  Type 'undefined' is not assignable to type 'Duplex | Pick<Agent, "addRequest"> | Agent | PromiseLike<AgentCallbackReturn>'.
```

**Comment by TooTallNate** [comment]
This code in this repository has been moved to the [`proxy-agents` monorepo](https://github.com/TooTallNate/proxy-agents), so I am closing this pull request. If you feel that this issue still exists as of the latest release, feel free to open a new issue over there.
