### ISSUE TITLE
New release for changes in PR #57 and PR #59

### ISSUE THREAD

**Issue by Apo-S** [TooTallNate/node-agent-base#60]
Could you create a new release, some of the necessary changes are already in the master branch, but this is no use because no recent changes in the npm package

**Comment by TooTallNate** [comment]
This code in this repository has been moved to the [`proxy-agents` monorepo](https://github.com/TooTallNate/proxy-agents), so I am closing this pull request. If you feel that this issue still exists as of the latest release, feel free to open a new issue over there.
