### ISSUE TITLE
Incorrect `agent.protocol` logic

### ISSUE THREAD

**Issue by szmarczak** [TooTallNate/node-agent-base#61]
https://github.com/TooTallNate/node-agent-base/blob/0288bc26f856dd0473a2923241dfbf1ab67b99b0/src/index.ts#L151-L156

This isn't compatible with other packages like https://github.com/szmarczak/http2-wrapper

The fix is just to omit `agent.protocol`:

https://github.com/nodejs/node/blob/3d53ff8ff0e721f908d8aff7a3709bc6dbb07ebb/lib/_http_client.js#L146-L149

**Comment by TooTallNate** [comment]
This code in this repository has been moved to the [`proxy-agents` monorepo](https://github.com/TooTallNate/proxy-agents), so I am closing this pull request. If you feel that this issue still exists as of the latest release, feel free to open a new issue over there.
