### ISSUE TITLE
Don't depend on stack trace format

### ISSUE THREAD

**Issue by rightaway** [TooTallNate/node-agent-base#63]
This depends on default stack trace output https://github.com/TooTallNate/node-agent-base/blob/0288bc26f856dd0473a2923241dfbf1ab67b99b0/src/index.ts#L18

With `Error.prepareStackTrace` https://v8.dev/docs/stack-trace-api#customizing-stack-traces there's no guarantee about its format or that it is even a string. Official v8 docs say that "User stack trace formatters are free to format the stack trace however they want and even return non-string values"

**Comment by nromito** [comment]
This is broken in node 16 due to the change in the stack trace output:

```
at request (node:https:353:10)
at Object.get (node:https:387:15)
```

**Comment by TooTallNate** [comment]
This code in this repository has been moved to the [`proxy-agents` monorepo](https://github.com/TooTallNate/proxy-agents), so I am closing this pull request. If you feel that this issue still exists as of the latest release, feel free to open a new issue over there.
